### ISSUE TITLE
[Documentation] Supported WMs?

### ISSUE THREAD

**Issue by rubyFeedback** [bbidulock/bbkeys#3]
Hello there,

I came to bbkeys from:

https://github.com/bbidulock/icewm

IceWM mentions it, so I suppose that it works there fine; and on openbox too I guess.

Would it be possible to briefly mention this in the README, which WMs are supported? Primarily so to get some confirmation before users may frantically try to get things to work when it may not work at all (right now I don't know, have to look at it first). Thanks for considering!

**Comment by bbidulock** [comment]
The README states that it supports Gnome/WMH and NetWM/EWMH compliant window managers.  This is not enough?
